FROM quay.io/fedora/fedora:36
RUN dnf -y install findutils git-core koji

# Force rebuild
RUN echo 2

COPY "prepare_ci.sh" "/usr/local/bin/"
RUN mkdir "/usr/local/src/rpms" && cd "/usr/local/src/rpms" && "/usr/local/bin/prepare_ci.sh"

ENTRYPOINT ["cp", "-r", "/usr/local/src/rpms/.", "-t"]
