FROM quay.io/fedora/fedora-minimal:rawhide
RUN microdnf -y update
RUN microdnf -y install findutils git-core koji make

# Force rebuild
RUN echo 4

COPY "prepare_ci.sh" "/usr/local/src/"
COPY "Makefile" "/usr/local/src/"
RUN make -j12 -C "/usr/local/src"

ENTRYPOINT ["cp", "-r", "/usr/local/src/rpms", "-t"]
