FROM registry.access.redhat.com/ubi9-minimal AS builder
RUN microdnf -y install git-core maven-openjdk17 rpm-libs

WORKDIR "/usr/local/src"

ENV java_deptools_hash='24c0b2f532f740d41c5d3859414aa22ee39c5bc1'
RUN echo "${java_deptools_hash}"
RUN git clone "https://github.com/mkoncek/java-deptools-native.git"

WORKDIR "/usr/local/src/java-deptools-native"

RUN git reset --hard "${java_deptools_hash}"
RUN mvn -B clean install

WORKDIR "/usr/local/src/javapackages-validator"

# First fetch dependencies without having sources
COPY "pom.xml" "/usr/local/src/javapackages-validator/"
RUN mvn -B clean install

COPY "src/" "/usr/local/src/javapackages-validator/src/"
RUN mvn -B clean install

################################################################################

FROM docker.io/library/alpine:3.16.2
RUN apk add rpm openjdk17-jre-headless

COPY --from=builder "/usr/local/src/javapackages-validator/target/dependency/" "/opt/javapackages-validator/dependency/"
COPY --from=builder "/usr/local/src/javapackages-validator/target/validator.jar" "/opt/javapackages-validator/validator.jar"

ENTRYPOINT ["java", "--enable-preview", "--add-modules", "jdk.incubator.foreign", "--enable-native-access", "ALL-UNNAMED", "-jar", "/opt/javapackages-validator/validator.jar"]
