[.text-justify]
= Javapackages-validator
:source-highlighter: rouge

_Javapackages-validator_ is a tool used to test RPM files.
It executes checks implemented as Java classes over the set of provided RPM files.

== Usage
The tool is executed from command line using `java` command with the proper class path.
JVM of version 21 is required.

----
Main [optional flags] <test name> [validator flags] [-f|-u RPM files or directories to test]...
----

[NOTE]
Due to the usage of the Foreign Memory Accesss feature, JVM arguments must include: +
`--enable-preview --enable-native-access ALL-UNNAMED`.

Optional flags::
[horizontal]
`-h`, `--help`::: Print help message.
`-x`, `--debug`::: Display debug output.
`-r`, `--color`::: Display colored output.
[horizontal!]

Options for specifying validators::
[horizontal]
`-sp`, `--source-path`::: Additional `.java` source file or directory.
`-d`::: Output directory for the compiled source files.
`-cp`, `--class-path`::: Additional class path entry for the validators.
[horizontal!]

Options for specifying tested RPM files, can be specified multiple times::
[horizontal]
`-f`, `--file`::: File path of an RPM file.
`-u`, `--url`::: URL of an RPM file.
[horizontal!]

=== RPM files
The parameters specifying RPM files can either be RPM file paths or directories.
In case of directories, the tool recursively searches for RPM files found inside.

=== Validator arguments
The tool recursively finds all `.java` files present in the _source path_ directory, compiles them and places the results under the path specified as the _class path_.
Class path may already exist and contain `.class` files, this is useful to implement <<_recompilation, caching>>.
The entries on this class path are used to add additional validator classes to the tool.

Validator arguments can be immediately followed by space-separated square parentheses the contents of which will be passed as arguments to the validator.

.Example
[source, shell]
----
$ Main package.name.ClassName [ arg1 arg2 'arg 3' ] -f file.rpm
----

[#_recompilation]
==== Recompilation
If the directory pointed to by the `--class-path` parameter exists, then the tool searches for files inside and inspects their modification time.
Recompilation is caused by any of these conditions:

- Class path directory is empty.
- Any *regular* file present on the class path is older than *any* file present on the source path
- Any directory on the class path has been modified after the latest modification time of any regular file present on the class path.
(This can mean that some `.class` files were deleted from the class path.)

Recompilation causes the class path directory to be cleaned before the newly compiled classes are placed there.

=== Service file
The file `META-INF/services/org.fedoraproject.javapackages.validator.spi.ValidatorFactory` contains a line-separated list of validator factory class names which are available to be executed.
This file will be copied from the source path to the class path and is expected to be present on the class path if source path is not specified.

The validator main argument passed to javapackages-validator must exactly match one of the names listed in either the service file or the service file on the built-in class path.

=== tmt
The tool contains another main class `MainTmt` which is intended to be invoked from within tmt tests.
When the validator is run from the tmt entry point, it requires the environment variables `TMT_TEST_DATA` and `TMT_TREE` to be defined.

Test execution from this entry point is configured using a configuration file named `javapackages-validator.yaml`.
This file can be located either in the root, i.e. the value of the `TMT_TREE` variable or in the `plans` directory of the project.

Every validator has an associated _test name_.
This is the result of the virtual `getTestName` function.
This name must be in the format of tmt tests, i.e. starting with `/`.
Test names are used to create report files.

==== Configuration
The following fields are allowed in the YAML configuration file.

_Fields starting with_ `/`::
The key is a tmt test name. The value of the field must be a list of strings. It will be passed as the arguments to the according validator.

`exclude-tests-matching`::
The value of this field is a list of strings.
The strings must be valid https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html[Java regular expressions].
If any of these patterns matches the test name of a validator, it will be skipped.

.Example of `javapackages-validator.yaml` configuration file
[source, yaml]
----
/java/bytecode_version: [":52"]
exclude-tests-matching:
  - "/java/.*"
----

==== Result
The tool generates both `.log` and `.html` reports with filenames matching the validator test names.
These files are placed in the directory `${TMT_TEST_DATA}/results`.

== Building
Project is built with Maven. Simply run:
[source, shell]
----
$ mvn install
----

== Custom validators
A custom validator must inherit from the `org.fedoraproject.javapackages.validator.Validator` class and have its name listed in the service file on the class path of the program.
Custom validators can override functions:

`void arguments(String[] args)`::
This is invoked during argument processing before the test execution to configure the validator from the arguments that were passed to it.

`void validate(Iterable<RpmFile> rpms)`::
This is the main function of the validator.
The validator is executed on a collection of RPM files.
The validator is supposed to call functions `debug`, `info`, `pass`, `fail`, `error` to provide information about its execution.
For details, see the section <<_result_states>>.

`String getTestName()`::
This is used to obtain the tmt test name. See also the `TmtTest` annotation class.

[#_result_states]
=== Result states
Each validator has a single result state.
The starting state is `skip`.
The state is overriden by calling corresponding methods of the `Validator` class.
The state listed lower in the following hierarchy overrides the previous states but not vice-versa.
Note that `debug` is not a result state, it only serves for the validator to provide verbose info.

.Result states
[horizontal]
`skip`::
A check was expectedly skipped because the validator determined so.
This can also mean that the property being tested was not present in the RPM under test.

`pass`::
Validation was run successfully and all the checks that were executed passed.

`info`::
The validator found a potential issue which does not affect validation results, but might be worth checking and fixing.

`warn`::
The validator only produced warning information.
Currently mostly unused.

`fail`::
At least one check failed.

`error`::
An error occured, for example invalid input or an unexpected state.
[horizontal!]
