:source-highlighter: rouge

= Javapackages-validator

Javapackages-validator is a tool used to test RPM files. It executes checks implemented as Java classes over the set of provided RPM files.

== Usage
The tool is executed from command line using `java` command with the proper class path. JVM of version at least 17 is required.

----
Main [optional flags] <validator class name> [validator flags] [-f|-u RPM files or directories to test]...
----

[NOTE]
Due to the usage of the Foreign Memory Accesss feature, JVM arguments must include: +
`--enable-preview --add-modules jdk.incubator.foreign --enable-native-access ALL-UNNAMED`.

Optional flags::
[horizontal]
`-h`, `--help`::: Print help message.
`-x`, `--debug`::: Display debug output.
`-r`, `--color`::: Display colored output.
[horizontal!]

Options for specifying validators::
[horizontal]
`-sp`, `--source-path`::: Additional `.java` source file or directory.
`-cp`, `--class-path`::: Additional class path entry or the output directory.
[horizontal!]

Options for specifying tested RPM files, can be specified multiple times::
[horizontal]
`-f`, `--file`::: File path of an RPM file.
`-u`, `--url`::: URL of an RPM file.
[horizontal!]

=== RPM files
The parameters specifying RPM files can either be RPM file paths or directories. In case of directories, the tool recursively searches for RPM files found inside.

=== Validator arguments
The tool recursively finds all `.java` files present in the _source path_ directory, compiles them and places the results under the path specified as the _class path_. Class path may already exist and contain `.class` files. This is useful to implement caching. The entries on this class path are used to add additional validator classes to the tool.

Validator arguments can be immediately followed by space-separated square parentheses the contents of which will be passed as arguments to the validator.

.Example
----
$ Main package.name.ClassName [ arg1 arg2 'arg 3' ] -f file.rpm
----

=== Service file
The file `META-INF/services/org.fedoraproject.javapackages.validator.Validator` contains a line-separated list of validator class names which are available to be executed. This file will be copied from the source path to the class path and is expected to be present on the class path if source path is not specified.

The validator main argument passed to _javapackages-validator_ must exactly match one of the names listed in either the service file or the service file on the built-in class path.

=== TMT
The tool contains another main class `MainTmt` which is intended to be invoked from within Tmt tests. When the validator is run from the Tmt entry point, it requires the environment variables `TMT_TEST_DATA` and `TMT_TREE` to be defined.

Test execution from this entry point is configured using a configuration file named `javapackages-validator.yaml`. This file can be located either in the root, i.e. the value of the `TMT_TREE` variable or in the `plans` directory of the project.

Every validator has an associated _test name_. This is the result of the virtual `getTestName` function. This name must be in the format of TMT tests, i.e. starting with `/`. Test names are used to create report files.

==== Configuration
The following fields are allowed in the YAML configuration file.

_Fields starting with_ `/`::
The key is a Tmt test name. The value of the field must be a list of strings. It will be passed as the arguments to the according validator.

`exclude-tests-matching`::
The value of this field is a list of strings. The strings must be valid https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html[Java regular expressions]. If any of these patterns matches the test name of a validator, it will be skipped.

.Example of `javapackages-validator.yaml` configuration file
[,yaml]
----
/java/bytecode_version: [":52"]
exclude-tests-matching:
  - "/java/.*"
----

==== Result
The tool generates both `.log` and `.html` reports with filenames matching the validator test names.

== Building
Project is built with maven. Simply run:
----
$ mvn install
----

The project currently requires a https://github.com/mkoncek/java-deptools-native.git[custom fork] of the _java-deptools-native_ project.

In order to build this project you need to build and install this forked project also with Maven.

== Custom validators
A custom validator must inherit from the `org.fedoraproject.javapackages.validator.Validator` class and have its name listed in the service file on the class path of the program. Custom validators can override functions:

`void arguments(String[] args)`::
This is invoked during argument processing before the test execution to configure the validator from the arguments that were passed to it.

`void validate(Iterable<RpmFile> rpms)`::
This is the main function of the validator. The validator is executed on a collection of RPM files. The validator is supposed to call functions `debug`, `info`, `pass`, `fail`, `error` to provide information about its execution. the resulting state is based on the hierarchy of the result types in the reverse order as listed previously. The default state is `info`, `debug` is not an actual state.

`String getTestName()`::
This is used to obtain the TMT test name. See also the `TmtTest` annotation class.
